CREATE DATABASE IF NOT EXISTS tournamentDB;

USE tournamentDB;

/* SEQUENCE 1 */
CREATE SEQUENCE tournamentDB.seq1
AS INT
START WITH 1
INCREMENT BY 1;

/* TOURNAMENTS TABLE */
CREATE TABLE IF NOT EXISTS TOURNAMENTS (
    tournamentID INT PRIMARY KEY DEFAULT NEXT VALUE FOR tournamentDB.seq1,
    tournamentName VARCHAR(100) NOT NULL
);

/* SEQUENCE 2 */
CREATE SEQUENCE tournamentDB.seq2
AS INT
START WITH 1
INCREMENT BY 1;

/* COMPETITORS TABLE */
CREATE TABLE IF NOT EXISTS COMPETITORS (
    competitorID INT PRIMARY KEY DEFAULT NEXT VALUE FOR tournamentDB.seq2,
    competitorFirstName VARCHAR(100) NOT NULL,
    competitorLastName VARCHAR(100) NOT NULL,
    tournamentID INT,

    FOREIGN KEY (tournamentID)
    REFERENCES TOURNAMENTS(tournamentID)
    ON DELETE CASCADE
);