CREATE DATABASE IF NOT EXISTS tournamentDB;

USE tournamentDB;

/* TOURNAMENTS TABLE */
CREATE TABLE IF NOT EXISTS TOURNAMENTS (
    tournamentID INT AUTO_INCREMENT PRIMARY KEY,
    tournamentName VARCHAR(100) NOT NULL
);

/* COMPETITORS TABLE */
CREATE TABLE IF NOT EXISTS COMPETITORS (
    competitorID INT AUTO_INCREMENT PRIMARY KEY,
    competitorFirstName VARCHAR(100) NOT NULL,
    competitorLastName VARCHAR(100) NOT NULL,
    tournamentID INT,

    FOREIGN KEY (tournamentID)
    REFERENCES TOURNAMENTS(tournamentID)
    ON DELETE CASCADE
);